// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swpvrnddajcyfmxxrahf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3cHZybmRkYWpjeWZteHhyYWhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0ODE1NTgsImV4cCI6MjA2NjA1NzU1OH0.1MOA7NezEdEN9BqYkDfpoK-9CCiFcr5iKglCTDGG-4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);